"use client";

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    pt: {
        // Hero Section
        'hero.badge': 'Soluções digitais para o seu negócio crescer',
        'hero.title.part1': 'Venda mais,',
        'hero.title.part2': 'ganhe visibilidade',
        'hero.title.part3': 'e seja referência',
        'hero.subtitle': 'Desenvolvo sistemas e sites sob medida para resolver problemas reais do seu negócio — organização, vendas, atendimento e imagem profissional no mercado.',
        'hero.cta': 'Solicitar Orçamento',
        'hero.viewProjects': 'Ver Projetos',
        'hero.scroll': 'Role',
        'hero.outcome1': 'Mais vendas',
        'hero.outcome2': 'Menos retrabalho',
        'hero.outcome3': 'Marca forte',
        'hero.outcome4': 'Clientes satisfeitos',
        'hero.outcome5': 'Tempo economizado',
        'hero.outcome6': 'Crescimento previsível',
        'hero.outcome7': 'Decisões mais seguras',
        'hero.visual.label': 'Projeto em destaque',
        'hero.clients.label': 'Empresas que confiam na Energon',
        'hero.testimonial.nav': 'Depoimento',
        'hero.testimonial1.quote': 'O sistema superou nossas expectativas. Nossa equipe trabalha com mais clareza e nossos clientes percebem a diferença.',
        'hero.testimonial1.author': 'Marina Costa',
        'hero.testimonial1.role': 'Diretora de Operações',
        'hero.testimonial1.company': 'Nexus Labs',
        'hero.testimonial2.quote': 'Antes perdíamos horas com planilhas. Hoje temos tudo organizado e vendemos com muito mais confiança.',
        'hero.testimonial2.author': 'Rafael Mendes',
        'hero.testimonial2.role': 'CEO',
        'hero.testimonial2.company': 'Voltex',
        'hero.testimonial3.quote': 'Nossa marca ficou mais forte e passamos a ser referência no setor. Entrega no prazo e suporte de verdade.',
        'hero.testimonial3.author': 'Camila Rocha',
        'hero.testimonial3.role': 'Head de Produto',
        'hero.testimonial3.company': 'Helix Group',

        // Outcome bridge (hero → services)
        'bridge.label': 'O que muda no seu negócio',
        'bridge.title': 'Menos problema no dia a dia. Mais resultado no caixa e no mercado.',
        'bridge.pains.label': 'Você se identifica com alguma dessas situações?',
        'bridge.pain1': 'Perco vendas por desorganização',
        'bridge.pain2': 'Tudo ainda vive em planilha',
        'bridge.pain3': 'Minha marca não passa confiança',
        'bridge.pain4': 'Não tenho clareza dos números',
        'bridge.outcome1.title': 'Mais vendas',
        'bridge.outcome1.desc': 'Processos claros e presença digital que converte trazem mais pedidos e fechamentos.',
        'bridge.outcome2.title': 'Mais visibilidade',
        'bridge.outcome2.desc': 'Sua empresa aparece, é encontrada e lembrada pelos clientes certos.',
        'bridge.outcome3.title': 'Mais respeito',
        'bridge.outcome3.desc': 'Imagem profissional que faz o mercado levar seu negócio a sério.',
        'bridge.outcome4.title': 'Menos retrabalho',
        'bridge.outcome4.desc': 'Sua equipe para de apagar incêndio e foca no que gera dinheiro.',
        'bridge.cta.text': 'Cada negócio é diferente. Veja abaixo como posso ajudar no seu caso.',
        'bridge.cta.link': 'Ver como posso ajudar',
        'bridge.stat.projects': 'Projetos entregues',
        'bridge.stat.satisfaction': 'Clientes satisfeitos',
        'bridge.stat.response': 'Prazo de resposta',

        // Navigation
        'nav.about': 'Sobre',
        'nav.services': 'Serviços',
        'nav.portfolio': 'Portfólio',
        'nav.process': 'Processo',
        'nav.contact': 'Contato',
        'nav.cta': 'Orçamento',

        // Footer
        'footer.tagline': 'Sistemas e sites sob medida para empresas que querem crescer com respeito no mercado.',
        'footer.marquee1': 'Mais vendas',
        'footer.marquee2': 'Marca forte',
        'footer.marquee3': 'Menos retrabalho',
        'footer.marquee4': 'Clientes fiéis',
        'footer.marquee5': 'Crescimento',
        'footer.marquee6': 'Visibilidade',
        'footer.marquee7': 'Resultados',
        'footer.navigation': 'Navegação',
        'footer.connect': 'Conectar',
        'footer.rights': 'Todos os direitos reservados.',
        'footer.admin': 'Área administrativa',

        // About Section
        'about.header.title': 'Por que empresas escolhem',
        'about.header.highlight': 'trabalhar comigo?',
        'about.header.subtitle': 'Não sou apenas mais um desenvolvedor. Sou um parceiro que entende seu negócio e entrega soluções que geram resultado — mais vendas, mais organização e mais credibilidade.',
        'about.benefit1.title': 'Desenvolvimento Rápido',
        'about.benefit1.description': 'Seu sistema pronto em semanas, não meses. Economize tempo e comece a lucrar mais rápido.',
        'about.benefit1.highlight': '3x mais rápido',
        'about.benefit2.title': 'Melhor Custo-Benefício',
        'about.benefit2.description': 'Sistemas sob medida sem custo de agência. Pague apenas pelo que você realmente precisa.',
        'about.benefit2.highlight': 'Até 60% mais barato',
        'about.benefit3.title': 'Suporte Garantido',
        'about.benefit3.description': 'Nunca fique na mão. Suporte direto comigo, sem intermediários ou filas de atendimento.',
        'about.benefit3.highlight': 'Resposta em 24h',
        'about.results.clients': 'Clientes Satisfeitos',
        'about.results.projects': 'Projetos Entregues',
        'about.results.support': 'Suporte Disponível',
        'about.whatYouGet.title': 'O que você ganha trabalhando comigo',
        'about.whatYouGet.subtitle': 'Resultados que você sente no dia a dia',
        'about.whatYouGet.item1': 'Solução feita sob medida para o seu negócio',
        'about.whatYouGet.item2': 'Imagem profissional que transmite confiança',
        'about.whatYouGet.item3': 'Fácil de usar — você e sua equipe aprendem rápido',
        'about.whatYouGet.item4': 'Funciona no celular, tablet e computador',
        'about.whatYouGet.item5': 'Suporte e ajustes inclusos por 3 meses',
        'about.whatYouGet.item6': 'O sistema é seu — sem surpresas nem dependência',
        'about.cta.title': 'Pronto para transformar sua ideia em realidade?',
        'about.cta.subtitle': 'Vamos conversar sobre seu projeto sem compromisso',
        'about.cta.button': 'Solicitar Orçamento Gratuito',
        'about.brand.label': 'Marca',
        'about.brand.tagline': 'Soluções digitais que crescem com o seu negócio',
        'about.brand.since': 'Desde 2024',

        // Services Section
        'services.title.prefix': 'Como posso',
        'services.title.highlight': 'ajudar você',
        'services.subtitle': 'Cada empresa tem uma dor diferente. Estas são as formas mais comuns de transformar problema em resultado.',
        'services.item1.title': 'Controle total do negócio',
        'services.item1.desc': 'Vendas, estoque, clientes e equipe em um só lugar. Menos confusão, mais lucro.',
        'services.item2.title': 'Seu produto ou serviço online',
        'services.item2.desc': 'Lance sua ideia no mercado com uma plataforma profissional que transmite confiança e gera receita.',
        'services.item3.title': 'Menos trabalho repetido',
        'services.item3.desc': 'Elimine tarefas manuais e libere seu time para o que realmente gera dinheiro.',
        'services.item4.title': 'Clareza para decidir',
        'services.item4.desc': 'Veja os números do seu negócio de forma simples e tome decisões com mais segurança.',
        'services.item5.title': 'Tudo funcionando junto',
        'services.item5.desc': 'WhatsApp, pagamentos, estoque — integrado para você não perder tempo nem cliente.',
        'services.item6.title': 'Presença online que converte',
        'services.item6.desc': 'Site profissional que passa credibilidade, aparece bem no Google e traz contatos qualificados.',

        // Process Section
        'process.title.prefix': 'Como',
        'process.title.highlight': 'Trabalhamos',
        'process.subtitle': 'Transparência total do início ao fim.',
        'process.step1.title': '1. Briefing e Entendimento',
        'process.step1.desc': 'Reunião inicial para entender sua dor, objetivos e requisitos do projeto. Aqui definimos o escopo.',
        'process.step2.title': '2. Proposta e Design',
        'process.step2.desc': 'Apresentação da solução, orçamento e visual do projeto. Você aprova antes de qualquer avanço.',
        'process.step3.title': '3. Construção com acompanhamento',
        'process.step3.desc': 'Desenvolvimento com entregas parciais para você acompanhar cada etapa e pedir ajustes.',
        'process.step4.title': '4. Entrega e Suporte',
        'process.step4.desc': 'Colocamos no ar, treinamos sua equipe e seguimos ao seu lado após a entrega.',

        // Differentiators Section
        'diff.title': 'Por que escolher meus',
        'diff.highlight': 'Serviços?',
        'diff.subtitle': 'Foco no que importa para o seu negócio: vender mais, trabalhar melhor e ser levado a sério no mercado.',
        'diff.item1.title': 'Não perca clientes',
        'diff.item1.desc': 'Site e sistema rápidos. Quem espera demais, vai para o concorrente.',
        'diff.item2.title': 'Tranquilidade',
        'diff.item2.desc': 'Seus dados e os dos seus clientes protegidos, para você dormir em paz.',
        'diff.item3.title': 'Pronto para crescer',
        'diff.item3.desc': 'A solução evolui junto com sua empresa — sem precisar começar do zero.',
        'diff.item4.title': 'Imagem profissional',
        'diff.item4.desc': 'Detalhes que fazem sua marca ser levada a sério e gerar mais confiança.',

        // Portfolio Section
        'portfolio.title.prefix': 'Projetos',
        'portfolio.title.highlight': 'Entregues',
        'portfolio.subtitle': 'Projetos reais que mostram como transformamos desafios de negócio em resultados concretos.',
        'portfolio.viewAll': 'Ver todos os projetos',
        'portfolio.viewDetails': 'Ver Detalhes',
        'portfolio.madeWith': 'Como foi feito',
        'portfolio.noImages': 'Nenhuma imagem do processo anexada ainda.',
        'portfolio.filterAll': 'Todos',
        'portfolio.modal.showcase': 'Projeto em destaque',
        'portfolio.modal.liveDemo': 'Ver demonstração',
        'portfolio.modal.techStack': 'Foco do projeto',
        'portfolio.modal.close': 'Fechar',
        'portfolio.modal.footer': 'Energon © 2026',

        // CTA Section (Final)
        'cta.badge': 'Inicie sua jornada',
        'cta.main.title': 'Pronto para transformar seu negócio?',
        'cta.main.subtitle': 'Vamos tirar sua ideia do papel e criar algo extraordinário juntos.',
        'cta.main.button': 'Começar Agora',

        // Contact Section
        'contact.title': 'Vamos conversar?',
        'contact.subtitle': 'Preencha o formulário e entrarei em contato o mais breve possível para discutirmos seu projeto.',
        'contact.email': 'Email',
        'contact.phone': 'WhatsApp',
        'contact.location': 'Localização',
        'contact.form.name': 'Nome',
        'contact.form.email': 'Email',
        'contact.form.subject': 'Assunto',
        'contact.form.message': 'Mensagem',
        'contact.form.namePlaceholder': 'Seu nome',
        'contact.form.emailPlaceholder': 'seu@email.com',
        'contact.form.subjectPlaceholder': 'Quero um sistema para...',
        'contact.form.messagePlaceholder': 'Descreva brevemente sua ideia...',
        'contact.form.submit': 'Enviar Mensagem',
        'contact.form.sending': 'Enviando...',
        'contact.form.success': 'Mensagem enviada com sucesso! Responderei em breve.',
        'contact.form.error': 'Erro ao enviar mensagem',
        'contact.fastResponse.title': 'Resposta Rápida',
        'contact.fastResponse.desc': 'Normalmente respondo a todas as consultas em até 24 horas. Seu projeto é importante para mim, e estou ansioso para discutir como podemos trabalhar juntos.',
        'contact.chatNow': 'Conversar no WhatsApp',
    },
    en: {
        // Hero Section
        'hero.badge': 'Digital solutions to grow your business',
        'hero.title.part1': 'Sell more,',
        'hero.title.part2': 'gain visibility',
        'hero.title.part3': 'and earn respect',
        'hero.subtitle': 'I build custom systems and websites that solve real business problems — organization, sales, customer service, and a professional market presence.',
        'hero.cta': 'Request Quote',
        'hero.viewProjects': 'View Projects',
        'hero.scroll': 'Scroll',
        'hero.outcome1': 'More sales',
        'hero.outcome2': 'Less rework',
        'hero.outcome3': 'Strong brand',
        'hero.outcome4': 'Happy customers',
        'hero.outcome5': 'Time saved',
        'hero.outcome6': 'Predictable growth',
        'hero.outcome7': 'Smarter decisions',
        'hero.visual.label': 'Featured project',
        'hero.clients.label': 'Companies that trust Energon',
        'hero.testimonial.nav': 'Testimonial',
        'hero.testimonial1.quote': 'The system exceeded our expectations. Our team works with more clarity and our customers notice the difference.',
        'hero.testimonial1.author': 'Marina Costa',
        'hero.testimonial1.role': 'Operations Director',
        'hero.testimonial1.company': 'Nexus Labs',
        'hero.testimonial2.quote': 'We used to lose hours on spreadsheets. Now everything is organized and we sell with much more confidence.',
        'hero.testimonial2.author': 'Rafael Mendes',
        'hero.testimonial2.role': 'CEO',
        'hero.testimonial2.company': 'Voltex',
        'hero.testimonial3.quote': 'Our brand got stronger and we became a reference in our industry. On-time delivery and real support.',
        'hero.testimonial3.author': 'Camila Rocha',
        'hero.testimonial3.role': 'Head of Product',
        'hero.testimonial3.company': 'Helix Group',

        // Outcome bridge (hero → services)
        'bridge.label': 'What changes for your business',
        'bridge.title': 'Fewer daily headaches. More revenue and market credibility.',
        'bridge.pains.label': 'Do any of these sound familiar?',
        'bridge.pain1': 'I lose sales because of disorganization',
        'bridge.pain2': 'Everything still lives in spreadsheets',
        'bridge.pain3': 'My brand does not build trust',
        'bridge.pain4': 'I lack clarity on my numbers',
        'bridge.outcome1.title': 'More sales',
        'bridge.outcome1.desc': 'Clear processes and a converting digital presence bring more orders and deals.',
        'bridge.outcome2.title': 'More visibility',
        'bridge.outcome2.desc': 'Your company shows up, gets found, and is remembered by the right customers.',
        'bridge.outcome3.title': 'More respect',
        'bridge.outcome3.desc': 'A professional image that makes the market take your business seriously.',
        'bridge.outcome4.title': 'Less rework',
        'bridge.outcome4.desc': 'Your team stops firefighting and focuses on what makes money.',
        'bridge.cta.text': 'Every business is different. See below how I can help in your case.',
        'bridge.cta.link': 'See how I can help',
        'bridge.stat.projects': 'Projects delivered',
        'bridge.stat.satisfaction': 'Satisfied clients',
        'bridge.stat.response': 'Response time',

        // Navigation
        'nav.about': 'About',
        'nav.services': 'Services',
        'nav.portfolio': 'Portfolio',
        'nav.process': 'Process',
        'nav.contact': 'Contact',
        'nav.cta': 'Get Quote',

        // Footer
        'footer.tagline': 'Custom systems and websites for businesses that want to grow with market respect.',
        'footer.marquee1': 'More sales',
        'footer.marquee2': 'Strong brand',
        'footer.marquee3': 'Less rework',
        'footer.marquee4': 'Loyal customers',
        'footer.marquee5': 'Growth',
        'footer.marquee6': 'Visibility',
        'footer.marquee7': 'Results',
        'footer.navigation': 'Navigation',
        'footer.connect': 'Connect',
        'footer.rights': 'All rights reserved.',
        'footer.admin': 'Admin area',

        // About Section
        'about.header.title': 'Why companies choose to',
        'about.header.highlight': 'work with me?',
        'about.header.subtitle': "I'm not just another developer. I'm a partner who understands your business and delivers results — more sales, better organization, and more credibility.",
        'about.benefit1.title': 'Fast Development',
        'about.benefit1.description': 'Your system ready in weeks, not months. Save time and start profiting faster.',
        'about.benefit1.highlight': '3x faster',
        'about.benefit2.title': 'Best Value',
        'about.benefit2.description': 'Custom systems without agency overhead. Pay only for what you really need.',
        'about.benefit2.highlight': 'Up to 60% cheaper',
        'about.benefit3.title': 'Guaranteed Support',
        'about.benefit3.description': 'Never be stranded. Direct support from me, no middlemen or ticket queues.',
        'about.benefit3.highlight': '24h response',
        'about.results.clients': 'Satisfied Clients',
        'about.results.projects': 'Projects Delivered',
        'about.results.support': 'Support Available',
        'about.whatYouGet.title': 'What you get working with me',
        'about.whatYouGet.subtitle': 'Results you feel in everyday work',
        'about.whatYouGet.item1': 'A solution tailored to your business',
        'about.whatYouGet.item2': 'A professional image that builds trust',
        'about.whatYouGet.item3': 'Easy to use — your team learns fast',
        'about.whatYouGet.item4': 'Works on mobile, tablet, and desktop',
        'about.whatYouGet.item5': 'Support and adjustments included for 3 months',
        'about.whatYouGet.item6': 'The system is yours — no surprises or lock-in',
        'about.cta.title': 'Ready to turn your idea into reality?',
        'about.cta.subtitle': "Let's talk about your project without commitment",
        'about.cta.button': 'Request Free Quote',
        'about.brand.label': 'Brand',
        'about.brand.tagline': 'Digital solutions that grow with your business',
        'about.brand.since': 'Since 2024',

        // Services Section
        'services.title.prefix': 'How I can',
        'services.title.highlight': 'help you',
        'services.subtitle': 'Every business has a different pain point. These are the most common ways to turn problems into results.',
        'services.item1.title': 'Full business control',
        'services.item1.desc': 'Sales, inventory, customers, and team in one place. Less confusion, more profit.',
        'services.item2.title': 'Your product or service online',
        'services.item2.desc': 'Launch your idea with a professional platform that builds trust and generates revenue.',
        'services.item3.title': 'Less repetitive work',
        'services.item3.desc': 'Remove manual tasks and free your team for what actually makes money.',
        'services.item4.title': 'Clarity to decide',
        'services.item4.desc': 'See your business numbers in a simple way and make decisions with confidence.',
        'services.item5.title': 'Everything working together',
        'services.item5.desc': 'WhatsApp, payments, inventory — integrated so you never lose time or customers.',
        'services.item6.title': 'Online presence that converts',
        'services.item6.desc': 'A professional site that builds credibility, ranks well, and brings qualified leads.',

        // Process Section
        'process.title.prefix': 'How We',
        'process.title.highlight': 'Work',
        'process.subtitle': 'Full transparency from start to finish.',
        'process.step1.title': '1. Briefing and Discovery',
        'process.step1.desc': 'Initial meeting to understand your pain points, goals and project requirements. Scope defined here.',
        'process.step2.title': '2. Proposal and Design',
        'process.step2.desc': 'Solution presentation, quote, and project visuals. You approve before anything moves forward.',
        'process.step3.title': '3. Build with check-ins',
        'process.step3.desc': 'Development with partial deliveries so you follow each step and request adjustments.',
        'process.step4.title': '4. Delivery and Support',
        'process.step4.desc': 'We go live, train your team, and stay by your side after delivery.',

        // Differentiators Section
        'diff.title': 'Why Choose My',
        'diff.highlight': 'Services?',
        'diff.subtitle': 'Focus on what matters for your business: sell more, work better, and be taken seriously in the market.',
        'diff.item1.title': "Don't lose customers",
        'diff.item1.desc': 'Fast site and system. People who wait too long go to your competitor.',
        'diff.item2.title': 'Peace of mind',
        'diff.item2.desc': 'Your data and your customers\' data protected, so you can rest easy.',
        'diff.item3.title': 'Ready to grow',
        'diff.item3.desc': 'The solution evolves with your company — without starting from scratch.',
        'diff.item4.title': 'Professional image',
        'diff.item4.desc': 'Details that make your brand trustworthy and respected.',

        // Portfolio Section
        'portfolio.title.prefix': 'Delivered',
        'portfolio.title.highlight': 'Projects',
        'portfolio.subtitle': 'Real projects showing how we turn business challenges into concrete results.',
        'portfolio.viewAll': 'View all projects',
        'portfolio.viewDetails': 'View Details',
        'portfolio.madeWith': 'How it was made',
        'portfolio.noImages': 'No process images attached yet.',
        'portfolio.filterAll': 'All',
        'portfolio.modal.showcase': 'Project showcase',
        'portfolio.modal.liveDemo': 'View live demo',
        'portfolio.modal.techStack': 'Project focus',
        'portfolio.modal.close': 'Close',
        'portfolio.modal.footer': 'Energon © 2026',

        // CTA Section (Final)
        'cta.badge': 'Start your journey',
        'cta.main.title': 'Ready to transform your business?',
        'cta.main.subtitle': "Let's take your idea off the paper and create something extraordinary together.",
        'cta.main.button': 'Get Started Now',

        // Contact Section
        'contact.title': "Let's talk?",
        'contact.subtitle': 'Fill out the form and I will contact you as soon as possible to discuss your project.',
        'contact.email': 'Email',
        'contact.phone': 'WhatsApp',
        'contact.location': 'Location',
        'contact.form.name': 'Name',
        'contact.form.email': 'Email',
        'contact.form.subject': 'Subject',
        'contact.form.message': 'Message',
        'contact.form.namePlaceholder': 'Your name',
        'contact.form.emailPlaceholder': 'your@email.com',
        'contact.form.subjectPlaceholder': 'I need a system for...',
        'contact.form.messagePlaceholder': 'Briefly describe your idea...',
        'contact.form.submit': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.form.success': 'Message sent successfully! I will reply soon.',
        'contact.form.error': 'Error sending message',
        'contact.fastResponse.title': 'Fast Response',
        'contact.fastResponse.desc': 'I typically respond to all inquiries within 24 hours. Your project is important to me, and I look forward to discussing how we can work together.',
        'contact.chatNow': 'Chat on WhatsApp',
    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('pt');

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations.pt] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
